# Generated by Django 5.1.4 on 2025-01-28 16:23

import estacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('cidade', models.CharField(blank=True, choices=estacao.models.Estacao.get_cidade_choices, max_length=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uf', models.CharField(choices=[('item1', 'SP'), ('item2', 'DF')], default='item1', max_length=10)),
                ('outorga_estacao', models.CharField(blank=True, choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'REVOGADA'), ('item4', 'AFILIADA - TV JORNAL DE LIMEIRA'), ('item5', 'AFILIADA - TV COSTA NORTE'), ('item6', 'AFILIADA - TV CULTURA PAULISTA'), ('item7', 'OUTROS - INFORMAR EM COMENTÁRIOS')], default='item1', max_length=30)),
                ('canal_virtual', models.CharField(max_length=30)),
                ('potencia_projeto', models.CharField(help_text='Potência de projeto em W', max_length=30, verbose_name='Potência de Projeto/Licença')),
                ('potencia_operacao', models.CharField(help_text='Potência de operação em W', max_length=30)),
                ('sfn', models.CharField(blank=True, choices=[('item1', 'SIM'), ('item2', 'NÃO')], max_length=10)),
                ('sfn_com', models.CharField(blank=True, help_text='Digite todas as cidades que fazem SFN com essa estação, separadas por vírgula', max_length=200)),
                ('sfn_id', models.CharField(blank=True, help_text='Deixe em branco se a estação não faz SFN', max_length=10)),
                ('equipe', models.CharField(help_text='Equipe de manutenção responsável', max_length=10)),
                ('responsabilidade_operacao', models.CharField(help_text='Empresa responsável pela operação e manutenção da estação', max_length=100)),
                ('status_operacao', models.CharField(choices=[('item1', 'OPERACIONAL'), ('item2', 'SEM OPERAÇÃO'), ('item3', 'OPERANDO SEM LICENÇA')], max_length=100, verbose_name='Situação da estação retransmissora')),
                ('fabricante_tx', models.CharField(blank=True, choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE'), ('item3', 'HITACHI'), ('item4', 'SCREEN'), ('item5', 'LINEAR (CONVERTIDO)')], max_length=100)),
                ('modelo_tx', models.CharField(max_length=100)),
                ('codigo_homolog_tx', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de homologação do transmissor')),
                ('fabricante_antena_tx', models.CharField(choices=[('item1', 'IDEAL'), ('item2', 'DIGITAL'), ('item3', 'POLIDESIGN'), ('item4', 'IF TELECOM'), ('item5', 'LUMICOM'), ('item6', 'ORIGINAL TELECOM'), ('item7', 'PAINEL'), ('item8', 'POLITELCO'), ('item9', 'TRANSTEL')], max_length=100)),
                ('modelo_antena_tx', models.CharField(max_length=100)),
                ('azimute', models.FloatField(blank=True, help_text='Azimute/Direção de orientação da Antena e relação ao norte verdadeiro', max_length=100, null=True, verbose_name='Azimute/Orientação')),
                ('fabricante_linha_tx', models.CharField(blank=True, help_text='Linha/cabo de Transmissão - Fabricante', max_length=100, null=True, verbose_name='Fabricante da linha de transmissão')),
                ('comp_linha_tx', models.FloatField(blank=True, help_text='Linha/cabo de Transmissão - Comprimento', max_length=100, null=True, verbose_name='Comprimento da linha de transmissão')),
                ('fabricante_rx', models.CharField(help_text='Tecsys, Anywave, Hitachi etc', max_length=100)),
                ('modelo_rx', models.CharField(max_length=100)),
                ('fabricante_antena_rx', models.CharField(max_length=100)),
                ('diametro_antena_rx', models.FloatField(help_text='Diâmetro da antena de recepção de satélite em metros', max_length=100)),
                ('tipo_torre', models.CharField(choices=[('item1', 'AUTOSUPORTADA'), ('item2', 'ESTAIADA'), ('item3', 'ALVENARIA'), ('item4', 'AP'), ('item5', 'CAIXA D AGUA'), ('item6', 'PRÉDIO'), ('item7', 'TUBULÃO DE FERRO'), ('item8', 'TUBULÃO GALVANIZADO')], max_length=100)),
                ('altura_torre', models.CharField(help_text='Altura da torre em metros', max_length=100)),
                ('proprietario_torre', models.CharField(help_text='CNPJ ou razão social', max_length=100)),
                ('fabricante_ar_condicionado', models.CharField(blank=True, help_text='Consul, Eletrolux etc', max_length=100)),
                ('modelo_ar_condicionado', models.CharField(max_length=100)),
                ('status_telemetria', models.CharField(choices=[('item1', 'SIM'), ('item2', 'NÃO')], help_text='Sim = Instalado, Não = não instalado', max_length=100)),
                ('proprietario_terreno', models.CharField(max_length=100)),
                ('seguro_estacao', models.CharField(choices=[('item1', 'SIM'), ('item2', 'NÃO')], max_length=100)),
                ('energia_paga_por', models.CharField(help_text='PM / PMSP / FPA etc', max_length=100)),
                ('agua_paga_por', models.CharField(help_text='PM / PMSP / FPA etc', max_length=100)),
                ('aluguel_pago_por', models.CharField(help_text='PM / PMSP / FPA etc', max_length=100)),
                ('iptu_pago_por', models.CharField(help_text='PM / PMSP / FPA etc', max_length=100)),
                ('tipo_abrigo', models.CharField(help_text='Alvenaria, container etc', max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(max_length=500)),
                ('cep', models.CharField(blank=True, help_text='CEP do endereço da estação', max_length=100, null=True)),
                ('anexo_contrato_estacao', models.FileField(blank=True, help_text='Anexo do contrato em PDF', null=True, upload_to='pdfs/')),
                ('comentarios', models.TextField(blank=True, help_text='Insira outras informações relevantes sobre a estação')),
            ],
            options={
                'verbose_name': 'Estação',
                'verbose_name_plural': 'Estações',
                'db_table': 'rede_estacao',
                'ordering': ['cidade'],
            },
        ),
    ]
