# Generated by Django 5.1.4 on 2025-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('canal_virtual', models.CharField(max_length=30)),
                ('potencia_projeto', models.CharField(help_text='Potência de projeto em W', max_length=30)),
                ('potencia_operacao', models.CharField(help_text='Potência de operação em W', max_length=30)),
                ('sfn', models.CharField(blank=True, max_length=10)),
                ('sfn_id', models.CharField(blank=True, help_text='Deixe em branco se a estação não faz SFN', max_length=10)),
                ('equipe', models.CharField(help_text='Equipe de manutenção responsável', max_length=10)),
                ('responsabilidade_operacao', models.CharField(help_text='Empresa responsável pela operação e manutenção da estação', max_length=100)),
                ('status_operacao', models.CharField(max_length=100)),
                ('status_telemetria', models.CharField(max_length=100)),
                ('proprietario_torre', models.CharField(max_length=100)),
                ('proprietario_terreno', models.CharField(max_length=100)),
                ('energia_paga_por', models.CharField(max_length=100)),
                ('agua_paga_por', models.CharField(max_length=100)),
                ('aluguel_pago_por', models.CharField(max_length=100)),
                ('iptu_pago_por', models.CharField(max_length=100)),
                ('tipo_abrigo', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(max_length=500)),
                ('comentarios', models.TextField(blank=True, help_text='Insira outras informações relevantes sobre a estação')),
            ],
            options={
                'verbose_name': 'Estação',
                'verbose_name_plural': 'Estações',
                'db_table': 'rede_estacao',
            },
        ),
    ]
