# Generated by Django 5.1.4 on 2025-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('canal_virtual', models.CharField(max_length=30)),
                ('potencia_projeto', models.CharField(max_length=30)),
                ('potencia_operacao', models.CharField(max_length=30)),
                ('sfn', models.CharField(max_length=10)),
                ('equipe', models.CharField(max_length=10)),
                ('operacao', models.CharField(max_length=100)),
                ('status_operacao', models.CharField(max_length=100)),
                ('status_telemetria', models.CharField(max_length=100)),
                ('proprietario_torre', models.CharField(max_length=100)),
                ('pgto_energia', models.CharField(max_length=100)),
                ('pgto_aluguel', models.CharField(max_length=100)),
                ('pgto_agua', models.CharField(max_length=100)),
                ('proprietario_terreno', models.CharField(max_length=100)),
                ('tipo_abrigo', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(max_length=500)),
                ('comentarios', models.TextField()),
            ],
            options={
                'verbose_name': 'Estação',
                'verbose_name_plural': 'Estações',
                'db_table': 'rede_estacao',
            },
        ),
    ]
