# Generated by Django 5.1.4 on 2025-01-10 16:23

import estacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='cidade',
            field=models.CharField(blank=True, choices=estacao.models.Estacao.get_cidade_choices, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='sfn',
            field=models.TextField(blank=True, help_text='Selecione as cidades que fazem SFN com essa estação'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='uf',
            field=models.CharField(blank=True, choices=estacao.models.Estacao.get_uf_choices, max_length=100, null=True),
        ),
    ]
