# Generated by Django 5.1.4 on 2025-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='anexo_contrato_estacao',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
