# Generated by Django 5.1.4 on 2025-01-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='diametro_antena_rx',
            field=models.FloatField(blank=True, help_text='Diâmetro da antena de recepção de satélite em metros', max_length=100, null=True),
        ),
    ]
