# Generated by Django 5.1.4 on 2025-01-10 16:41

import estacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0002_alter_estacao_cidade_alter_estacao_sfn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='sfn',
            field=models.CharField(blank=True, choices=estacao.models.Estacao.get_cidade_choices, help_text='Selecione a cidade que faz SFN com essa estação', max_length=100, null=True),
        ),
    ]
