# Generated by Django 5.1.4 on 2025-01-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0002_alter_estacao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='disponibilidade_30_dias',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
