# Generated by Django 5.1.4 on 2025-01-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0002_alter_estacao_diametro_antena_rx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_antena_rx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante da antena de recepção de satélite'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_rx',
            field=models.CharField(blank=True, help_text='Tecsys, Anywave, Hitachi etc', max_length=100, null=True, verbose_name='Fabricante receptor/excitador'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='modelo_ar_condicionado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do aparelho de ar condicionado'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='modelo_rx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo receptor/excitador'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='seguro_estacao',
            field=models.CharField(blank=True, choices=[('item1', 'SIM'), ('item2', 'NÃO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='status_telemetria',
            field=models.CharField(blank=True, choices=[('item1', 'SIM'), ('item2', 'NÃO')], help_text='Sim = Instalado, Não = não instalado', max_length=100, null=True, verbose_name='Status sistema de telemetria'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='tipo_torre',
            field=models.CharField(blank=True, choices=[('item1', 'AUTOSUPORTADA'), ('item2', 'ESTAIADA'), ('item3', 'ALVENARIA'), ('item4', 'AP'), ('item5', 'CAIXA D AGUA'), ('item6', 'PRÉDIO'), ('item7', 'TUBULÃO DE FERRO'), ('item8', 'TUBULÃO GALVANIZADO')], max_length=100, null=True),
        ),
    ]
