# Generated by Django 5.1.4 on 2025-01-15 21:22

import estacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0002_estacao_anexo_contrato_estacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='fabricante_ar_condicionado',
            field=models.CharField(blank=True, help_text='Consul, Eletrolux etc', max_length=100),
        ),
        migrations.AddField(
            model_name='estacao',
            name='fabricante_rx',
            field=models.CharField(blank=True, help_text='Tecsys, Anywave, Hitachi etc', max_length=100),
        ),
        migrations.AddField(
            model_name='estacao',
            name='fabricante_tx',
            field=models.CharField(blank=True, help_text='Tecsys, Anywave, Hitachi etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='agua_paga_por',
            field=models.CharField(help_text='PM / PMSP / FPA', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='altura_torre',
            field=models.CharField(default='', help_text='Altura da torre em metros', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='aluguel_pago_por',
            field=models.CharField(help_text='PM / PMSP / FPA', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='anexo_contrato_estacao',
            field=models.FileField(blank=True, help_text='Anexo do contrato em PDF', null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='diametro_antena_rx',
            field=models.CharField(default='', help_text='Diâmetro da antena de recepção de satélite em metros', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='energia_paga_por',
            field=models.CharField(help_text='PM / PMSP / FPA', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='iptu_pago_por',
            field=models.CharField(help_text='PM / PMSP / FPA', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='proprietario_torre',
            field=models.CharField(default='', help_text='CNPJ ou razão social', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='sfn',
            field=models.CharField(blank=True, choices=estacao.models.Estacao.get_cidade_choices, help_text='Selecione a cidade que faz SFN com essa estação', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='tipo_abrigo',
            field=models.CharField(blank=True, help_text='Alvenaria, container etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='tipo_torre',
            field=models.CharField(default='', help_text='Estaiada, autosuportada etc', max_length=100),
        ),
    ]
