# Generated by Django 5.1.4 on 2025-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0003_alter_estacao_fabricante_antena_rx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_antena_tx',
            field=models.CharField(blank=True, choices=[('item1', 'IDEAL'), ('item2', 'DIGITAL'), ('item3', 'POLIDESIGN'), ('item4', 'IF TELECOM'), ('item5', 'LUMICOM'), ('item6', 'ORIGINAL TELECOM'), ('item7', 'PAINEL'), ('item8', 'POLITELCO'), ('item9', 'TRANSTEL')], max_length=100, null=True, verbose_name='Fabricante da antena de transmissão'),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_tx',
            field=models.CharField(blank=True, choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE'), ('item3', 'HITACHI'), ('item4', 'SCREEN'), ('item5', 'LINEAR (CONVERTIDO)')], max_length=100, null=True),
        ),
    ]
