# Generated by Django 5.1.4 on 2025-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0003_alter_estacao_sfn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='pgto_agua',
        ),
        migrations.RemoveField(
            model_name='estacao',
            name='pgto_aluguel',
        ),
        migrations.RemoveField(
            model_name='estacao',
            name='pgto_energia',
        ),
        migrations.AddField(
            model_name='estacao',
            name='agua_paga_por',
            field=models.CharField(choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'PMSP')], default='item1', max_length=10),
        ),
        migrations.AddField(
            model_name='estacao',
            name='aluguel_pago_por',
            field=models.CharField(choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'PMSP')], default='item1', max_length=10),
        ),
        migrations.AddField(
            model_name='estacao',
            name='energia_paga_por',
            field=models.CharField(choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'PMSP')], default='item1', max_length=10),
        ),
        migrations.AddField(
            model_name='estacao',
            name='iptu_pago_por',
            field=models.CharField(choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'PMSP')], default='item1', max_length=10),
        ),
    ]
