# Generated by Django 5.1.4 on 2025-01-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0003_estacao_fabricante_ar_condicionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='altura_torre',
            field=models.CharField(help_text='Altura da torre em metros', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='diametro_antena_rx',
            field=models.CharField(default='', help_text='Diâmetro da antena de recepção de satélite em metros', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_antena_rx',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_antena_tx',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_rx',
            field=models.CharField(help_text='Tecsys, Anywave, Hitachi etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_tx',
            field=models.CharField(help_text='Tecsys, Anywave, Hitachi etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='modelo_antena_tx',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='modelo_ar_condicionado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='modelo_rx',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='modelo_tx',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='proprietario_terreno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='proprietario_torre',
            field=models.CharField(help_text='CNPJ ou razão social', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='status_operacao',
            field=models.CharField(help_text='OPERACIONAL ou SEM OPERAÇÃO', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='status_telemetria',
            field=models.CharField(help_text='Instalado ou Não instalado', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='tipo_abrigo',
            field=models.CharField(help_text='Alvenaria, container etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='tipo_torre',
            field=models.CharField(help_text='Estaiada, autosuportada etc', max_length=100),
        ),
    ]
