# Generated by Django 5.1.4 on 2025-01-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0003_estacao_disponibilidade_30_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='disponibilidade_30_dias',
        ),
    ]
