# Generated by Django 5.1.4 on 2025-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0004_remove_estacao_pgto_agua_remove_estacao_pgto_aluguel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='tipo_torre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
