# Generated by Django 5.1.4 on 2025-01-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0004_alter_estacao_fabricante_antena_tx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_rx',
            field=models.CharField(blank=True, choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE'), ('item3', 'HITACHI'), ('item4', 'SCREEN'), ('item5', 'LINEAR (CONVERTIDO)')], help_text='Tecsys, Anywave, Hitachi etc', max_length=100, null=True, verbose_name='Fabricante receptor/excitador'),
        ),
    ]
