# Generated by Django 5.1.4 on 2025-01-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0004_alter_estacao_altura_torre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='sfn_com',
            field=models.CharField(blank=True, help_text='Digite todas as cidades que fazem SFN com essa estação, separadas por vírgula', max_length=200),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='agua_paga_por',
            field=models.CharField(help_text='PM / PMSP / FPA etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='aluguel_pago_por',
            field=models.CharField(help_text='PM / PMSP / FPA etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='energia_paga_por',
            field=models.CharField(help_text='PM / PMSP / FPA etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_antena_tx',
            field=models.CharField(choices=[('item1', 'IDEAL'), ('item2', 'DIGITAL'), ('item3', 'POLIDESIGN'), ('item4', 'IF TELECOM'), ('item5', 'LUMICOM'), ('item6', 'ORIGINAL TELECOM'), ('item7', 'PAINEL'), ('item8', 'POLITELCO'), ('item9', 'TRANSTEL')], max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='fabricante_tx',
            field=models.CharField(blank=True, choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE'), ('item3', 'HITACHI'), ('item4', 'SCREEN'), ('item5', 'LINEAR (CONVERTIDO)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='iptu_pago_por',
            field=models.CharField(help_text='PM / PMSP / FPA etc', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='sfn',
            field=models.CharField(blank=True, choices=[('item1', 'SIM'), ('item2', 'NÃO')], default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacao',
            name='status_telemetria',
            field=models.CharField(choices=[('item1', 'SIM'), ('item2', 'NÃO')], help_text='Sim = Instalado, Não = não instalado', max_length=100),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='tipo_torre',
            field=models.CharField(choices=[('item1', 'AUTOSUPORTADA'), ('item2', 'ESTAIADA'), ('item3', 'ALVENARIA'), ('item4', 'AP'), ('item5', 'CAIXA D AGUA'), ('item6', 'PRÉDIO'), ('item7', 'TUBULÃO DE FERRO'), ('item8', 'TUBULÃO GALVANIZADO')], max_length=100),
        ),
    ]
