# Generated by Django 5.1.4 on 2025-01-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0005_alter_estacao_fabricante_rx'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='ar_condicionado',
            field=models.CharField(blank=True, choices=[('item1', 'SIM'), ('item2', 'NÃO')], help_text='Sim - Possui, Não - Não possui', max_length=100, null=True, verbose_name='Ar condicionado'),
        ),
    ]
