# Generated by Django 5.1.4 on 2025-01-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0005_estacao_tipo_torre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='sfn_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
