# Generated by Django 5.1.4 on 2025-01-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0005_estacao_sfn_com_alter_estacao_agua_paga_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='seguro_estacao',
            field=models.CharField(choices=[('item1', 'SIM'), ('item2', 'NÃO')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
