# Generated by Django 5.1.4 on 2025-01-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0006_estacao_sfn_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacao',
            old_name='operacao',
            new_name='responsabilidade_operacao',
        ),
    ]
