# Generated by Django 5.1.4 on 2025-01-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0006_estacao_ar_condicionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='tipo_abrigo',
            field=models.CharField(choices=[('item1', 'ALVENARIA'), ('item2', 'CONTAINER')], help_text='Alvenaria, container etc', max_length=100, verbose_name='Tipo do abrigo'),
        ),
    ]
