# Generated by Django 5.1.4 on 2025-01-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0006_estacao_seguro_estacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='outorga_estacao',
            field=models.CharField(blank=True, choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'REVOGADA'), ('item3', 'OUTROS')], default='item1', max_length=30),
        ),
    ]
