# Generated by Django 5.1.4 on 2025-01-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0007_estacao_outorga_estacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='azimute',
            field=models.CharField(blank=True, help_text='Azimute/Direção de orientação da Antena e relação ao norte verdadeiro', max_length=100, null=True, verbose_name='Azimute/Orientação'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP do endereço da estação', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estacao',
            name='codigo_homolog_tx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de homologação do transmissor'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='comp_linha_tx',
            field=models.CharField(blank=True, help_text='Linha/cabo de Transmissão - Comprimento', max_length=100, null=True, verbose_name='Comprimento da linha de transmissão'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='fabricante_linha_tx',
            field=models.CharField(blank=True, help_text='Linha/cabo de Transmissão - Fabricante', max_length=100, null=True, verbose_name='Fabricante da linha de transmissão'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estacao',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='potencia_projeto',
            field=models.CharField(help_text='Potência de projeto em W', max_length=30, verbose_name='Potência de Projeto/Licença'),
        ),
    ]
