# Generated by Django 5.1.4 on 2025-01-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0007_rename_operacao_estacao_responsabilidade_operacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='tipo_torre',
        ),
    ]
