# Generated by Django 5.1.4 on 2025-01-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0007_alter_estacao_tipo_abrigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='sfn_com',
            field=models.TextField(blank=True, help_text='Digite todas as cidades que fazem SFN com essa estação, separadas por vírgula', null=True, verbose_name='SFN com'),
        ),
    ]
