# Generated by Django 5.1.4 on 2025-01-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0008_alter_estacao_sfn_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='FOTO1',
            field=models.ImageField(blank=True, null=True, upload_to='manutencao/', verbose_name='Foto da estação (1)'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='FOTO2',
            field=models.ImageField(blank=True, null=True, upload_to='manutencao/', verbose_name='Foto da estação (2)'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='FOTO3',
            field=models.ImageField(blank=True, null=True, upload_to='manutencao/', verbose_name='Foto da estação (3)'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='FOTO4',
            field=models.ImageField(blank=True, null=True, upload_to='manutencao/', verbose_name='Foto da estação (4)'),
        ),
        migrations.AddField(
            model_name='estacao',
            name='FOTO5',
            field=models.ImageField(blank=True, null=True, upload_to='manutencao/', verbose_name='Foto da estação (5)'),
        ),
    ]
