# Generated by Django 5.1.4 on 2025-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=50)),
                ('potencia_tx', models.CharField(max_length=100)),
                ('modelo_tx', models.CharField(max_length=100)),
                ('fabricante_antena_tx', models.CharField(max_length=100)),
                ('modelo_antena_tx', models.CharField(max_length=100)),
                ('modelo_rx', models.CharField(blank=True, max_length=100)),
                ('nivel_recepcao', models.CharField(blank=True, max_length=100)),
                ('fabricante_antena_rx', models.CharField(blank=True, max_length=100)),
                ('diametro_antena_rx', models.FloatField(blank=True, null=True)),
                ('tipo_torre', models.CharField(max_length=100)),
                ('altura_torre', models.CharField(max_length=100)),
                ('modelo_ar_condicionado', models.CharField(blank=True, max_length=100)),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dados Equipamentos',
                'verbose_name_plural': 'Dados Equipamentos',
                'db_table': 'rede_dados_equipamentos',
            },
        ),
    ]
