# Generated by Django 5.1.4 on 2025-01-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados_equipamentos',
            name='nivel_recepcao',
        ),
        migrations.AlterField(
            model_name='dados_equipamentos',
            name='altura_torre',
            field=models.CharField(help_text='Altura da torre em metros', max_length=100),
        ),
        migrations.AlterField(
            model_name='dados_equipamentos',
            name='comentarios',
            field=models.TextField(blank=True, help_text='Insira mais informações sobre os equipamentos dessa estação'),
        ),
        migrations.AlterField(
            model_name='dados_equipamentos',
            name='modelo_ar_condicionado',
            field=models.CharField(blank=True, help_text='Marca/Modelo do aparelho de ar-condicionado', max_length=100),
        ),
        migrations.AlterField(
            model_name='dados_equipamentos',
            name='modelo_rx',
            field=models.CharField(blank=True, help_text='Marca/Modelo do receptor', max_length=100),
        ),
        migrations.AlterField(
            model_name='dados_equipamentos',
            name='modelo_tx',
            field=models.CharField(help_text='Marca/Modelo do transmissor UHF', max_length=100),
        ),
        migrations.AlterField(
            model_name='dados_equipamentos',
            name='potencia_tx',
            field=models.CharField(help_text='Potência nominal do transmissor em Watts', max_length=100),
        ),
        migrations.AlterField(
            model_name='dados_equipamentos',
            name='tipo_torre',
            field=models.CharField(help_text='Ex.: Estaiada, autosuportada etc', max_length=100),
        ),
    ]
