# Generated by Django 5.1.4 on 2025-01-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processos_Anatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(default='', max_length=100)),
                ('uf', models.CharField(default='', max_length=10)),
                ('local_especifico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local específico da estação')),
                ('prazo_anatel', models.DateField(blank=True, null=True, verbose_name='Prazo limite junto à Anatel/MCOM')),
                ('acao', models.CharField(blank=True, choices=[('item1', 'ENTRAR EM OPERAÇÃO'), ('item2', 'PAGAR PPDUR'), ('item3', 'LICENCIAR'), ('item4', 'OUTROS')], default='item1', max_length=100, verbose_name='Ação')),
                ('relatorio_conformidade', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Relatório de conformidade')),
                ('laudo_vistoria', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Laudo de vistoria')),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processos Anatel',
                'verbose_name_plural': 'Processos Anatel',
                'db_table': 'rede_processos_anatel',
                'ordering': ['-prazo_anatel'],
            },
        ),
    ]
