# Generated by Django 5.1.4 on 2025-01-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_IBGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10)),
                ('prefeito', models.CharField(max_length=100)),
                ('area_territorial', models.FloatField(blank=True, null=True)),
                ('populacao', models.FloatField(blank=True, null=True)),
                ('densidade_demografica', models.FloatField(blank=True, null=True)),
                ('escolarizacao', models.FloatField(blank=True, null=True)),
                ('cobertura_feita_por', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dados Cidades',
                'verbose_name_plural': 'Dados Cidades',
                'db_table': 'rede_dados_ibge',
            },
        ),
    ]
