# Generated by Django 5.1.4 on 2025-01-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IBGE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_ibge',
            name='cobertura_tvc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
