# Generated by Django 5.1.4 on 2025-01-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IBGE', '0002_dados_ibge_cobertura_tvc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados_ibge',
            options={'ordering': ['cidade'], 'verbose_name': 'Dados Cidades', 'verbose_name_plural': 'Dados Cidades'},
        ),
    ]
