# Generated by Django 5.1.4 on 2025-01-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('ativo_fixo', models.CharField(max_length=100)),
                ('comentarios', models.TextField()),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventário',
                'db_table': 'rede_inventario',
            },
        ),
    ]
