# Generated by Django 5.1.4 on 2025-01-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['cidade'], 'verbose_name': 'Inventário', 'verbose_name_plural': 'Inventário'},
        ),
    ]
