# Generated by Django 5.1.4 on 2025-01-15 22:29

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='foto_ativo_frontal',
            field=models.ImageField(blank=True, help_text='Carregue uma foto da parte de frente do ativo', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='foto_ativo_traseira',
            field=models.ImageField(blank=True, help_text='Carregue uma foto da parte traseira do ativo', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cidade',
            field=models.CharField(blank=True, choices=inventario.models.Inventario.get_cidade_choices, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='comentarios',
            field=models.TextField(help_text='Insira informações relevantes sobre esse ativo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descricao',
            field=models.CharField(help_text='AR CONDICIONADO, TRANSMISSOR UHF, RECEPTOR, ANTENA RX, ANTENA TX', max_length=100),
        ),
    ]
