# Generated by Django 5.1.4 on 2025-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_foto_ativo_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='foto_ativo_frontal',
            field=models.ImageField(blank=True, help_text='Carregue uma foto da parte de frente do ativo', null=True, upload_to='fotos_ativos/'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='foto_ativo_traseira',
            field=models.ImageField(blank=True, help_text='Carregue uma foto da parte traseira do ativo', null=True, upload_to='fotos_ativos/'),
        ),
    ]
