# Generated by Django 5.1.4 on 2025-02-07 21:04

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_foto_ativo_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cidade',
            field=models.CharField(blank=True, choices=inventario.models.Inventario.get_cidade_choices, max_length=100, null=True, verbose_name='Cidade/Estação'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descricao',
            field=models.CharField(choices=[('item1', 'AR CONDICIONADO'), ('item2', 'TRANSMISSOR UHF'), ('item3', 'RECEPTOR SAT'), ('item4', 'ANTENA RX'), ('item5', 'ANTENA TX'), ('item6', 'OUTROS - DETALHAR EM COMENTÁRIOS')], max_length=100, verbose_name='Descrição do ativo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='equipe',
            field=models.CharField(choices=[('item1', 'SP-1'), ('item2', 'SP-2'), ('item2', 'SP-3'), ('item2', 'SP-4')], max_length=10, verbose_name='Equipe'),
        ),
    ]
