# Generated by Django 5.1.4 on 2025-02-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_inventario_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='equipe',
            field=models.CharField(choices=[('item1', 'SP-1'), ('item2', 'SP-2'), ('item3', 'SP-3'), ('item4', 'SP-4')], max_length=500, verbose_name='Equipe'),
        ),
    ]
