# Generated by Django 5.1.4 on 2025-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('energia_paga_por', models.CharField(choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'PMSP')], default='item1', max_length=10)),
                ('energia_paga_a', models.CharField(help_text='Digite o CNPJ ou CPF', max_length=100)),
                ('valor_conta_energia', models.FloatField(blank=True, help_text='Digite o último valor da conta', null=True)),
                ('aluguel_pago_por', models.CharField(choices=[('item1', 'FPA'), ('item2', 'PM'), ('item3', 'PMSP')], default='item1', max_length=10)),
                ('aluguel_paga_a', models.CharField(help_text='Digite o CNPJ ou CPF', max_length=100)),
                ('valor_conta_aluguel', models.FloatField(blank=True, help_text='Digite o último valor da conta', null=True)),
                ('agua_paga_por', models.CharField(max_length=100)),
                ('agua_paga_a', models.CharField(help_text='Digite o CNPJ ou CPF', max_length=100)),
                ('valor_conta_agua', models.FloatField(blank=True, help_text='Digite o último valor da conta', null=True)),
                ('iptu_pago_por', models.CharField(help_text='Digite ', max_length=100)),
                ('valor_conta_iptu', models.FloatField(blank=True, help_text='Digite o último valor da conta', null=True)),
            ],
            options={
                'verbose_name': 'Dados Pagamento',
                'verbose_name_plural': 'Dados Pagamento',
                'db_table': 'rede_dados_pagamento',
            },
        ),
    ]
