# Generated by Django 5.1.4 on 2025-01-23 17:23

import pagamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, choices=pagamentos.models.Dados_Pagamento.get_cidade_choices, max_length=100, null=True)),
                ('uf', models.CharField(choices=[('item1', 'SP'), ('item2', 'DF')], default='item1', max_length=10)),
                ('tipo_conta', models.CharField(choices=[('item1', 'ÁGUA'), ('item2', 'ENERGIA'), ('item3', 'ALUGUEL'), ('item4', 'IPTU'), ('item5', 'TELEFONE')], default='item1', max_length=100)),
                ('mes_referencia', models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, null=True)),
                ('conta_paga_a', models.CharField(help_text='Digite o CNPJ ou CPF', max_length=100)),
                ('razao_social_receptor', models.CharField(default='', help_text='Digite a razão social do CPF/CNPJ informado acima', max_length=100)),
                ('valor_bruto_conta', models.FloatField(blank=True, help_text='Digite o valor bruto da conta em R$', null=True)),
                ('valor_liquido_conta', models.FloatField(blank=True, help_text='Digite o valor líquido da conta em R$', null=True)),
                ('conta_digitalizada', models.ImageField(blank=True, null=True, upload_to='contas_digitalizadas/')),
                ('comentarios', models.TextField(blank=True, help_text='Escreva outras observações da conta. Ex.: Número de contrato, consumo no mês etc', null=True)),
            ],
            options={
                'verbose_name': 'Dados Pagamentos',
                'verbose_name_plural': 'Dados Pagamentos',
                'db_table': 'rede_dados_pagamento',
                'ordering': ['cidade'],
            },
        ),
    ]
