# Generated by Django 5.1.4 on 2025-01-10 17:22

import pagamentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_pagamento',
            old_name='agua_paga_a',
            new_name='conta_paga_a',
        ),
        migrations.RenameField(
            model_name='dados_pagamento',
            old_name='aluguel_pago_por',
            new_name='conta_paga_por',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='agua_paga_por',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='aluguel_paga_a',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='energia_paga_a',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='energia_paga_por',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='iptu_pago_por',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='valor_conta_agua',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='valor_conta_aluguel',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='valor_conta_energia',
        ),
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='valor_conta_iptu',
        ),
        migrations.AddField(
            model_name='dados_pagamento',
            name='mes_referencia',
            field=models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Decembro')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dados_pagamento',
            name='razao_social',
            field=models.CharField(default='', help_text='Digite a razão social do CPF/CNPJ informado acima', max_length=100),
        ),
        migrations.AddField(
            model_name='dados_pagamento',
            name='valor_bruto_conta',
            field=models.FloatField(blank=True, help_text='Digite o valor bruto da conta em R$', null=True),
        ),
        migrations.AddField(
            model_name='dados_pagamento',
            name='valor_liquido_conta',
            field=models.FloatField(blank=True, help_text='Digite o valor líquido da conta em R$', null=True),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='cidade',
            field=models.CharField(blank=True, choices=pagamentos.models.Dados_Pagamento.get_cidade_choices, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='uf',
            field=models.CharField(blank=True, choices=pagamentos.models.Dados_Pagamento.get_uf_choices, max_length=100, null=True),
        ),
    ]
