# Generated by Django 5.1.4 on 2025-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados_pagamento',
            options={'ordering': ['-mes_referencia'], 'verbose_name': 'Dados Pagamentos', 'verbose_name_plural': 'Dados Pagamentos'},
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='conta_digitalizada',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Conta digitalizada (PDF)'),
        ),
    ]
