# Generated by Django 5.1.4 on 2025-02-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_dados_pagamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_pagamento',
            name='comentarios',
            field=models.TextField(blank=True, help_text='Escreva outras observações da conta. Ex.: Número de contrato, consumo no mês etc', null=True, verbose_name='Comentários'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='conta_paga_a',
            field=models.CharField(help_text='Digite o CNPJ ou CPF', max_length=100, verbose_name='Conta paga à (CNPJ):'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='mes_referencia',
            field=models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, null=True, verbose_name='Mês de referência'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='razao_social_receptor',
            field=models.CharField(default='', help_text='Digite a razão social do CPF/CNPJ informado acima', max_length=100, verbose_name='Razão social do receptor'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='tipo_conta',
            field=models.CharField(choices=[('item1', 'ÁGUA'), ('item2', 'ENERGIA'), ('item3', 'ALUGUEL'), ('item4', 'IPTU'), ('item5', 'TELEFONE'), ('item6', 'MÃO DE OBRA'), ('item7', 'SERVIÇOS EVENTUAIS'), ('item8', 'CONTRATOS'), ('item9', 'OUTROS - DETALHAR EM COMENTÁRIOS')], default='item1', max_length=100, verbose_name='Tipo da conta'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='uf',
            field=models.CharField(choices=[('item1', 'SP'), ('item2', 'DF')], default='item1', max_length=10, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='valor_bruto_conta',
            field=models.FloatField(blank=True, help_text='Digite o valor bruto da conta em R$', null=True, verbose_name='Valor bruto da conta'),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='valor_liquido_conta',
            field=models.FloatField(blank=True, help_text='Digite o valor líquido da conta em R$', null=True, verbose_name='Valor líquido da conta'),
        ),
    ]
