# Generated by Django 5.1.4 on 2025-01-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_rename_agua_paga_a_dados_pagamento_conta_paga_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados_pagamento',
            old_name='razao_social',
            new_name='razao_social_receptor',
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='mes_referencia',
            field=models.CharField(blank=True, choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, null=True),
        ),
    ]
