# Generated by Django 5.1.4 on 2025-02-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_alter_dados_pagamento_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_pagamento',
            name='tipo_conta',
            field=models.CharField(choices=[('item1', 'ÁGUA'), ('item2', 'ENERGIA'), ('item3', 'ALUGUEL'), ('item4', 'IPTU'), ('item5', 'TELEFONE'), ('item6', 'MÃO DE OBRA'), ('item7', 'SERVIÇOS EVENTUAIS'), ('item8', 'CONTRATOS'), ('item9', 'CRÉDITO ROTATIVO (CAIXINHA)'), ('item10', 'OUTROS - DETALHAR EM COMENTÁRIOS')], default='item1', max_length=100, verbose_name='Tipo da conta'),
        ),
    ]
