# Generated by Django 5.1.4 on 2025-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_rename_razao_social_dados_pagamento_razao_social_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_pagamento',
            name='tipo_conta',
            field=models.CharField(choices=[('item1', 'ÁGUA'), ('item2', 'ENERGIA'), ('item3', 'ALUGUEL'), ('item3', 'IPTU')], default='item1', max_length=10),
        ),
    ]
