# Generated by Django 5.1.4 on 2025-01-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_dados_pagamento_tipo_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_pagamento',
            name='comentarios',
            field=models.TextField(blank=True, help_text='Escreva outras observações da conta. Ex.: Número de contrato, consumo no mês etc', null=True),
        ),
        migrations.AlterField(
            model_name='dados_pagamento',
            name='tipo_conta',
            field=models.CharField(choices=[('item1', 'ÁGUA'), ('item2', 'ENERGIA'), ('item3', 'ALUGUEL'), ('item4', 'IPTU'), ('item5', 'TELEFONE')], default='item1', max_length=100),
        ),
    ]
