# Generated by Django 5.1.4 on 2025-01-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_dados_pagamento_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados_pagamento',
            name='conta_paga_por',
        ),
    ]
