# Generated by Django 5.1.4 on 2025-01-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_remove_dados_pagamento_conta_paga_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados_pagamento',
            options={'verbose_name': 'Dados Pagamentos', 'verbose_name_plural': 'Dados Pagamentos'},
        ),
    ]
