# Generated by Django 5.1.4 on 2025-01-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0007_alter_dados_pagamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados_pagamento',
            options={'ordering': ['cidade'], 'verbose_name': 'Dados Pagamentos', 'verbose_name_plural': 'Dados Pagamentos'},
        ),
    ]
