# Generated by Django 5.1.4 on 2025-01-29 14:13

import telemetria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, choices=telemetria.models.Telemetria.get_cidade_choices, max_length=100, null=True)),
                ('uf', models.CharField(choices=[('item1', 'SP'), ('item2', 'DF')], default='item1', max_length=10)),
                ('versao_software', models.CharField(choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE V1'), ('item3', 'ANYWAVE V2'), ('item4', 'HITACHI')], default='item1', max_length=30)),
                ('numero_chip', models.CharField(default='', max_length=30)),
                ('id_chip', models.CharField(default='', max_length=30)),
                ('operadora', models.CharField(choices=[('item1', 'VIVO'), ('item2', 'CLARO'), ('item3', 'TIM'), ('item4', 'OI')], default='item1', max_length=30)),
                ('serial_number_modem', models.CharField(default='', max_length=50)),
                ('tipo_modem', models.CharField(choices=[('item1', 'USB (INTERNO)'), ('item2', 'ETHERNET (EXTERNO)')], default='item1', max_length=30)),
                ('modelo_modem', models.CharField(default='', max_length=100)),
                ('data_instalacao', models.DateField()),
                ('status', models.CharField(choices=[('item1', 'INSTALADO'), ('item2', 'NÃO INSTALADO POR FALTA DE SINAL'), ('item3', 'NÃO INSTALADO POR FALHA NO EQUIPAMENTO')], default='item1', max_length=100)),
                ('comentarios', models.TextField(help_text='Insira informações relevantes sobre esse sistema de telemetria')),
            ],
            options={
                'verbose_name': 'Telemetria',
                'verbose_name_plural': 'Telemetria',
                'db_table': 'rede_telemetria',
                'ordering': ['cidade'],
            },
        ),
    ]
