# Generated by Django 5.1.4 on 2025-01-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetria',
            options={'ordering': ['cidade'], 'verbose_name': 'Telemetria', 'verbose_name_plural': 'Telemetria'},
        ),
        migrations.AddField(
            model_name='telemetria',
            name='serial_number_modem',
            field=models.CharField(default='', max_length=50),
        ),
    ]
