# Generated by Django 5.1.4 on 2025-01-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0002_alter_telemetria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetria',
            name='tipo_modem',
            field=models.CharField(choices=[('item1', 'USB (INTERNO)'), ('item2', 'ETHERNET (EXTERNO)')], default='item1', max_length=30),
        ),
    ]
