# Generated by Django 5.1.4 on 2025-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0003_telemetria_tipo_modem'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetria',
            name='modelo_modem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='telemetria',
            name='comentarios',
            field=models.TextField(help_text='Insira informações relevantes sobre esse sistema de telemetria'),
        ),
    ]
