# Generated by Django 5.1.4 on 2025-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_Regulatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('canal_fisico', models.CharField(max_length=100)),
                ('status_anatel', models.CharField(max_length=100)),
                ('validade', models.CharField(max_length=100)),
                ('numero_fistel', models.CharField(max_length=100)),
                ('carater', models.CharField(max_length=20)),
                ('finalidade', models.CharField(max_length=100)),
                ('servico', models.CharField(max_length=100)),
                ('frequencia', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('altitude', models.CharField(max_length=100)),
                ('erp', models.CharField(max_length=100)),
                ('hci', models.CharField(max_length=100)),
                ('fase', models.CharField(max_length=100)),
                ('anexo_mancha_de_cobertura', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('anexo_licenca', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('comentarios', models.TextField()),
            ],
            options={
                'verbose_name': 'Dados Regulatórios',
                'verbose_name_plural': 'Dados Regulatórios',
                'db_table': 'rede_dados_regulatorios',
            },
        ),
    ]
