# Generated by Django 5.1.4 on 2025-01-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados_regulatorios',
            options={'ordering': ['cidade'], 'verbose_name': 'Dados Regulatórios', 'verbose_name_plural': 'Dados Regulatórios'},
        ),
    ]
