# Generated by Django 5.1.4 on 2025-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0002_alter_dados_regulatorios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='anexo_mancha_de_cobertura',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_projeto/'),
        ),
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='servico',
            field=models.CharField(help_text='RTVD, GTVD, ECRD, AM, FM', max_length=100),
        ),
    ]
