# Generated by Django 5.1.4 on 2025-01-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0003_alter_dados_regulatorios_anexo_mancha_de_cobertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_regulatorios',
            name='local_especifico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
