# Generated by Django 5.1.4 on 2025-01-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0004_dados_regulatorios_local_especifico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados_regulatorios',
            name='validade',
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='laudo_vistoria',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Laudo de vistoria'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='prazo_anatel',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo limite junto à Anatel/MCOM'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='relatorio_conformidade',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Relatório de conformidade'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='validade_licenca',
            field=models.DateField(blank=True, null=True, verbose_name='Validade da Licença'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='validade_uso_rf',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Uso RF'),
        ),
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='anexo_licenca',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Anexo da licença da estação'),
        ),
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='anexo_mancha_de_cobertura',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_projeto/', verbose_name='Anexo da imagem da mancha de cobertura'),
        ),
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='status_anatel',
            field=models.CharField(choices=[('item1', 'TV-C1 (Canal Outorgado - Aguardando Ato de RF)'), ('item2', 'TV-C2'), ('item3', 'TV-C3'), ('item4', 'TV-C4 (Canal Licenciado)'), ('item5', 'TV-C5 (Canal pendente de outorga)'), ('item6', 'AM-C4 (Canal Licenciado)'), ('item7', 'FM-C4 (Canal Licenciado)'), ('item8', 'PPDUR À PAGAR'), ('item9', 'À LICENCIAR'), ('item10', 'ENTRAR EM OPERAÇÃO'), ('item11', 'OUTROS')], help_text='Escolha um item', max_length=100),
        ),
    ]
