# Generated by Django 5.1.4 on 2025-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0005_remove_dados_regulatorios_validade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados_regulatorios',
            name='validade_licenca',
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='data_emissao_licenca',
            field=models.DateField(blank=True, null=True, verbose_name='Data da emissão da licença'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='observacao_anatel',
            field=models.CharField(blank=True, help_text='Por exemplo: responder exigências, entrar em operação, pagar TFI etc', max_length=200, null=True, verbose_name='Observação'),
        ),
    ]
