# Generated by Django 5.1.4 on 2025-01-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0006_remove_dados_regulatorios_validade_licenca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço da estação'),
        ),
    ]
