# Generated by Django 5.1.4 on 2025-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0007_alter_dados_regulatorios_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_regulatorios',
            name='azimute',
            field=models.FloatField(blank=True, help_text='Azimute/Direção de orientação da Antena e relação ao norte verdadeiro', max_length=100, null=True, verbose_name='Azimute/Orientação'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='codigo_homolog_tx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de homologação do transmissor'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='comp_linha_tx',
            field=models.FloatField(blank=True, help_text='Linha/cabo de Transmissão - Comprimento em metros', max_length=100, null=True, verbose_name='Comprimento da linha de transmissão'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='fabricante_antena_tx',
            field=models.CharField(choices=[('item1', 'IDEAL'), ('item2', 'DIGITAL'), ('item3', 'POLIDESIGN'), ('item4', 'IF TELECOM'), ('item5', 'LUMICOM'), ('item6', 'ORIGINAL TELECOM'), ('item7', 'PAINEL'), ('item8', 'POLITELCO'), ('item9', 'TRANSTEL')], default='item1', max_length=100, verbose_name='Fabricante da antena de transmissão'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='fabricante_linha_tx',
            field=models.CharField(blank=True, help_text='Linha/cabo de Transmissão - Fabricante', max_length=100, null=True, verbose_name='Fabricante da linha de transmissão'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='fabricante_tx',
            field=models.CharField(choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE'), ('item3', 'HITACHI'), ('item4', 'SCREEN'), ('item5', 'LINEAR (CONVERTIDO)')], default='item1', max_length=100, verbose_name='Fabricante do transmissor'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='modelo_antena_tx',
            field=models.CharField(default='', max_length=100, verbose_name='Modelo da antena de transmissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='modelo_tx',
            field=models.CharField(default='', max_length=100, verbose_name='Modelo do transmissor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='pot_operacao',
            field=models.FloatField(default=0, max_length=100, verbose_name='Potência de operação aprovada em kW'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='tipo_antena_tx',
            field=models.CharField(default='', help_text='Ex.: Slot', max_length=100, verbose_name='Tipo da antena de transmissão'),
            preserve_default=False,
        ),
    ]
