# Generated by Django 5.1.4 on 2025-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0008_dados_regulatorios_azimute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_regulatorios',
            name='tilt',
            field=models.FloatField(blank=True, help_text='Tilt da antena de transmissão em graus °', max_length=100, null=True, verbose_name='Tilt'),
        ),
    ]
