# Generated by Django 5.1.4 on 2025-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorios', '0009_dados_regulatorios_tilt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_regulatorios',
            name='codigo_homolog_tx_aux',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de homologação do transmissor auxiliar'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='fabricante_tx_aux',
            field=models.CharField(blank=True, choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE'), ('item3', 'HITACHI'), ('item4', 'SCREEN'), ('item5', 'LINEAR (CONVERTIDO)')], default='item1', max_length=100, null=True, verbose_name='Fabricante do transmissor auxiliar'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='modelo_linha_tx',
            field=models.CharField(blank=True, help_text='Linha/cabo de Transmissão - Modelo', max_length=100, null=True, verbose_name='Modelo da linha de transmissão'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='modelo_tx_aux',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do transmissor auxiliar'),
        ),
        migrations.AddField(
            model_name='dados_regulatorios',
            name='pot_max_aux',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Potência máxima do transmissor auxiliar'),
        ),
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='codigo_homolog_tx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de homologação do transmissor principal'),
        ),
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='fabricante_tx',
            field=models.CharField(choices=[('item1', 'TECSYS'), ('item2', 'ANYWAVE'), ('item3', 'HITACHI'), ('item4', 'SCREEN'), ('item5', 'LINEAR (CONVERTIDO)')], default='item1', max_length=100, verbose_name='Fabricante do transmissor principal'),
        ),
        migrations.AlterField(
            model_name='dados_regulatorios',
            name='modelo_tx',
            field=models.CharField(max_length=100, verbose_name='Modelo do transmissor principal'),
        ),
    ]
