# Generated by Django 5.1.4 on 2025-01-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio_Manutencao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(choices=[('item1', 'SP'), ('item2', 'DF')], default='item1', max_length=10)),
                ('data_reclamacao', models.DateTimeField(blank=True, null=True)),
                ('data_manutencao', models.DateTimeField(blank=True, null=True)),
                ('autor_manutencao', models.CharField(blank=True, max_length=100)),
                ('tipo_manutencao', models.CharField(choices=[('item1', 'PREVENTIVA'), ('item2', 'CORRETIVA'), ('item3', 'EMERGENCIAL')], default='item1', max_length=10)),
                ('comentario_manutencao', models.TextField(blank=True)),
                ('pot_direta', models.FloatField(blank=True, null=True)),
                ('pot_refletida', models.FloatField(blank=True, null=True)),
                ('exciter_power', models.FloatField(blank=True, null=True)),
                ('nivel_CN', models.FloatField(blank=True, null=True)),
                ('nivel_recepcao', models.FloatField(blank=True, null=True)),
                ('VISTA_FRONTAL_TX', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('VISTA_TRASEIRA_TX', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ANTENA_DE_RECEPCAO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ANTENA_DE_TRANSMISSAO_E_DA_TORRE', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_1_INTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_2_INTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_1_EXTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_2_EXTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('VISAO_GERAL', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
            ],
            options={
                'verbose_name': 'Relatório Manutenção',
                'verbose_name_plural': 'Relatório Manutenção',
                'db_table': 'rede_relatorio_manutencao',
            },
        ),
    ]
