# Generated by Django 5.1.4 on 2025-01-14 20:21

import manutencao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio_Manutencao',
            fields=[
                ('cidade', models.CharField(blank=True, choices=manutencao.models.Relatorio_Manutencao.get_cidade_choices, max_length=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uf', models.CharField(choices=[('item1', 'SP'), ('item2', 'DF')], default='item1', max_length=10)),
                ('data_reclamacao', models.DateTimeField(blank=True, null=True)),
                ('data_manutencao', models.DateTimeField(blank=True, null=True)),
                ('disponibilidade', models.FloatField(blank=True, editable=False, null=True)),
                ('tecnico_manutencao', models.CharField(choices=[('item1', 'ARI LIMA'), ('item2', 'RODRIGO AGUADO'), ('item3', 'PEDRO'), ('item4', 'TANIS'), ('item5', 'ALEXANDRE COSME'), ('item6', 'ELIAS')], default='item1', max_length=50)),
                ('tipo_manutencao', models.CharField(choices=[('item1', 'PREVENTIVA'), ('item2', 'CORRETIVA'), ('item3', 'EMERGENCIAL')], default='item1', max_length=10)),
                ('comentario_manutencao', models.TextField(blank=True)),
                ('pot_direta', models.FloatField(blank=True, help_text='Leitura da potência direta em W', null=True)),
                ('pot_refletida', models.FloatField(blank=True, help_text='Leitura da potência direta em W', null=True)),
                ('exciter_power', models.FloatField(blank=True, help_text='Leitura do nível de excitação em dBm', null=True)),
                ('nivel_CN', models.FloatField(blank=True, help_text='Leitura de C/N em dB', null=True)),
                ('nivel_recepcao', models.FloatField(blank=True, help_text='Leitura do nível de recepção em dBm', null=True)),
                ('VISTA_FRONTAL_TX', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('VISTA_TRASEIRA_TX', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ANTENA_DE_RECEPCAO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ANTENA_DE_TRANSMISSAO_E_DA_TORRE', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_1_INTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_2_INTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_1_EXTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('ABRIGO_2_EXTERNO', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
                ('VISAO_GERAL', models.ImageField(blank=True, null=True, upload_to='manutencao/')),
            ],
            options={
                'verbose_name': 'Relatório Manutenção',
                'verbose_name_plural': 'Relatório Manutenção',
                'db_table': 'rede_relatorio_manutencao',
                'ordering': ['cidade'],
            },
        ),
    ]
