# Generated by Django 5.1.4 on 2025-01-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio_manutencao',
            old_name='disponibilidade',
            new_name='difference',
        ),
    ]
