# Generated by Django 5.1.4 on 2025-01-10 18:30

import manutencao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio_manutencao',
            name='autor_manutencao',
        ),
        migrations.AddField(
            model_name='relatorio_manutencao',
            name='tecnico_manutencao',
            field=models.CharField(choices=[('item1', 'ARI LIMA'), ('item2', 'RODRIGO AGUADO'), ('item3', 'PEDRO'), ('item4', 'TANIS'), ('item5', 'ALEXANDRE COSME'), ('item6', 'ELIAS')], default='item1', max_length=50),
        ),
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='cidade',
            field=models.CharField(blank=True, choices=manutencao.models.Relatorio_Manutencao.get_cidade_choices, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='exciter_power',
            field=models.FloatField(blank=True, help_text='Leitura do nível de excitação em dBm', null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='nivel_CN',
            field=models.FloatField(blank=True, help_text='Leitura de C/N em dB', null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='nivel_recepcao',
            field=models.FloatField(blank=True, help_text='Leitura do nível de recepção em dBm', null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='pot_direta',
            field=models.FloatField(blank=True, help_text='Leitura da potência direta em W', null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='pot_refletida',
            field=models.FloatField(blank=True, help_text='Leitura da potência direta em W', null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='uf',
            field=models.CharField(blank=True, choices=manutencao.models.Relatorio_Manutencao.get_uf_choices, max_length=100, null=True),
        ),
    ]
