# Generated by Django 5.1.4 on 2025-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio_manutencao',
            name='disponibilidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
