# Generated by Django 5.1.4 on 2025-01-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_relatorio_manutencao_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='disponibilidade',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
