# Generated by Django 5.1.4 on 2025-01-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_rename_disponibilidade_relatorio_manutencao_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='pot_refletida',
            field=models.CharField(blank=True, default='', help_text='Leitura da potência direta em W', max_length=10),
            preserve_default=False,
        ),
    ]
