# Generated by Django 5.1.4 on 2025-01-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_alter_relatorio_manutencao_pot_refletida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorio_manutencao',
            options={'ordering': ['-data_manutencao'], 'verbose_name': 'Relatório Manutenção', 'verbose_name_plural': 'Relatório Manutenção'},
        ),
    ]
