# Generated by Django 5.1.4 on 2025-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_alter_relatorio_manutencao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio_manutencao',
            name='tecnico_manutencao',
            field=models.CharField(choices=[('item1', 'ARI/RODRIGO AGUADO - SP1'), ('item2', 'PEDRO/TANIS - SP2'), ('item3', 'ELIAS - SP3'), ('item4', 'ALEXANDRE COSME/ANDRÉ - SP4')], default='item1', max_length=50),
        ),
    ]
